name: Delete Merged Branch

on:
  pull_request:
    types:
      - closed

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Delete branch if merged
        uses: octokit/request-action@v2.x
        with:
          route: DELETE /repos/:owner/:repo/git/refs/heads/:branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event.pull_request.merged == true
