name: Delete Merged Branch

on:
  pull_request:
    types:
      - closed

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the branch was merged
        if: github.event.pull_request.merged == true
        run: echo "Branch was merged, proceeding with deletion."

      - name: Prevent deletion of protected branches
        if: github.event.pull_request.merged == true && github.event.pull_request.head.ref != 'main' && github.event.pull_request.head.ref != 'develop'
        uses: octokit/request-action@v2.x
        with:
          route: DELETE /repos/sedataskan/kitApp/git/refs/heads/${{ github.event.pull_request.head.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
